### ISSUE TITLE
FYI Display issues on Dell PowerEdge R740 server

### ISSUE THREAD

**Issue by pief** [tsani/tetrefis#1]
Hello,

Just so that you know, I did something completely unexpected and booted tetrEFIs on a Dell PowerEdge R740 Server and get display issues:
![tetrefis-r740](https://user-images.githubusercontent.com/2843983/80748239-e5e07f00-8b24-11ea-91d9-bff1456423fe.jpg)

Why in heaven's name would I boot it on a server you might ask? Good question! Because I wanted to use it to try to debug UEFI PXE boot issues and was originally assuming that the corrupted graphics stem from a corrupted TFTP transfer. But then I noticed that the same display issues occur when booting it from the local EFI partition, so something else must be with the R740's UEFI BIOS. 

Not really expecting you to fix this, just FYI ;)

**Comment by tsani** [comment]
This is amazing. Thanks for sharing! It makes you the first ever "real-world" user of tetrEFIs that I know of ;)
